FROM mysql:8.0.32

ENV MYSQL_ROOT_PASSWORD=f%RFZ331
# schema name
ENV MYSQL_DATABASE=DevOpsExpertsDB
# db username
ENV MYSQL_USER=amir
# db user password
ENV MYSQL_PASSWORD=e%RP9331

EXPOSE 3301

CMD ["mysqld"]
